name = "nuxt-fullstack-test"  # Your Worker's name (must be unique within your Cloudflare account)
main = "./worker.js"        # Path to your Worker script (we'll create this in the next step)
compatibility_date = "2024-10-27" # Use a recent compatibility date for latest features
workers_dev = false         # Set to false for production deployment to your domain
route = "yourdomain.com/*"   # Route to handle all requests for your domain

[site]
bucket = "./.output/public"   # Path to your static frontend assets